language: python

services:
  - docker

before_install:
- docker pull wealizedigital/alastria-node-t-checker:latest

script:
- docker run wealizedigital/alastria-node-t-checker /bin/sh -c "cd /code && poetry run mypy ."
- docker run wealizedigital/alastria-node-t-checker /bin/sh -c "cd /code && poetry run python -m pytest --cov=validator"
