language: python

services:
  - docker

before_install:
- docker pull javaguirre/node-t-checker:latest

script:
- docker run javaguirre/node-t-checker /bin/sh -c "cd /code && poetry run mypy ."
- docker run javaguirre/node-t-checker /bin/sh -c "cd /code && poetry run python -m pytest --cov=validator"
